# Generated by Django 4.0.4 on 2022-04-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, verbose_name='Имя пользователя')),
                ('chat_id', models.TextField(blank=True, verbose_name='Номер чата')),
                ('steam', models.TextField(blank=True, verbose_name='Логин стим')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('game', models.TextField(blank=True, verbose_name='Игра')),
                ('active', models.BooleanField(default=True, verbose_name='Поиск')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
