# Generated by Django 4.0.4 on 2022-04-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_profile_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='choice',
            field=models.TextField(blank=True, verbose_name='Выбранный пользователь'),
        ),
    ]
